#!/bin/bash

### BEGIN INIT INFO
# Provides:          domoweb
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start DomoWeb UI for Domogik
### END INIT INFO

#This file is part of B{Domogik} project (U{http://www.domogik.org}).
#
#License
#=======
#
#B{Domogik} is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#B{Domogik} is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Domogik. If not, see U{http://www.gnu.org/licenses}.

# source application-specific settings
CUSTOM_PATH=""

[ -f /etc/conf.d/domoweb ] && . /etc/conf.d/domoweb
[ -f /etc/default/domoweb ] && . /etc/default/domoweb

NAME=Domoweb.py
DAEMON=/usr/bin/python
LOGFILE=/var/log/domoweb/console.log

if [ $UID != 0 ];then
    echo "Must be run with root privileges";
    exit 1;
fi

function start_domoweb {
    echo -n " * Starting DomoWeb..."
    [ ! -d /var/log/domoweb ] && \
        /bin/mkdir /var/log/domoweb
    /bin/chown -Rf ${DOMOWEB_USER}:root /var/log/domoweb
    /bin/su - ${DOMOWEB_USER} -c "$DAEMON $DOMOWEB_PATH/$NAME >$LOGFILE 2>&1 &"
    if [ $? -gt 0 ]; then
        echo " An error occured during DomoWeb startup."
        exit 1
    else
        echo " Done."
    fi
}

function stop_domoweb {
    echo -n " * Stopping DomoWeb..."
    PIDS=`ps ax | grep "$NAME" | grep -v grep | awk '{print $1}'`
    for pid in $PIDS; do
        kill -9 $pid 2>/dev/null 1>&2
    done
    echo " Done."
}

function status_domoweb {
    PIDS=`ps ax | grep "$NAME" | grep -v grep | awk '{print $1}'`
    for pid in $PIDS; do
        echo " * DomoWeb is running under pid $pid"
        exit 0
    done
    echo " * DomoWeb is not running"
}

case "$1" in
    start)
        PIDS=`ps ax | grep "$NAME" | grep -v grep | awk '{print $1}'`
        if [ -z $PIDS ]; then
            start_domoweb
        else
            echo "Domoweb seems to be running ($PIDS). Please stop it." && exit 0
        fi
    ;;
    stop)
        stop_domoweb
    ;;
    status)
        status_domoweb
    ;;
    restart)
        stop_domoweb
        sleep 3
        start_domoweb
    ;;
    *)
    echo "usage: $0 {start|stop|restart|status|killall}"
esac
exit 0
