#!/bin/bash

### BEGIN INIT INFO
# Provides:          domoweb
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start DomoWeb UI for Domogik
### END INIT INFO

#This file is part of B{Domogik} project (U{http://www.domogik.org}).
#
#License
#=======
#
#B{Domogik} is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#B{Domogik} is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Domogik. If not, see U{http://www.gnu.org/licenses}.

# source application-specific settings
CUSTOM_PATH=""

[ -f /etc/conf.d/domoweb ] && . /etc/conf.d/domoweb
[ -f /etc/default/domoweb ] && . /etc/default/domoweb


PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$CUSTOM_PATH:
DAEMON=$(which dmg_domoweb)
LOGFILE=/var/log/domoweb/console.log
PIDFILE=/var/run/domoweb/domoweb.pid

if [ $UID != 0 ];then
    echo "Must be run with root privileges";
    exit 1;
fi

function start_django {
    echo -n " * Starting DomoWeb..."
    /bin/su - ${DOMOWEB_USER} -c "$DAEMON >$LOGFILE 2>&1 &"
    if [ $? -gt 0 ]; then
        echo " An error occured during DomoWeb startup."
        exit 1
    else
        echo " Done."
    fi
}

function stop_django {
    echo -n " * Stopping DomoWeb..."
    #for pid in `ps ax | grep "$DAEMON" | grep -v grep | awk '{print $1}'`; do
    #    kill -9 $pid 2>/dev/null 1>&2
    #done
    kill $(cat $PIDFILE)
    sleep 1
    kill -9 $(cat $PIDFILE)
    [ -f $PIDFILE ] && rm $PIDFILE
    echo " Done."
}

function status_django {
    [ ! -f $PIDFILE ] && echo " * DomoWeb is not running (can't find pid file)"
    RUNNING=$(pgrep "$DAEMON" | grep -c $(cat $PIDFILE))
    if [ $RUNNING -eq 1 ]; then
        echo " * DomoWeb is running"
    else
        echo " * DomoWeb is not running"
    fi

    kill $(cat $PIDFILE)
    sleep 1
    kill -9 $(cat $PIDFILE)
    echo " Done."
}

case "$1" in
    start)
    start_django
    ;;
    stop)
    stop_django
    ;;
    restart)
    stop_django
    sleep 3
    start_django
    ;;
    *)
    echo "usage: $0 {start|stop|restart|status}"
esac
exit 0
