#!/bin/sh -e
#
# summary of how this script can be called:
#        * <new-preinst> install
#        * <new-preinst> install <old-version>
#        * <new-preinst> upgrade <old-version>
#        * <old-preinst> abort-upgrade <new-version>
#

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
DATADIR=/var/lib/domoweb
LOGDIR=/var/log/domoweb
set -e

set +e
/usr/sbin/a2enmod proxy
/usr/sbin/a2enmod proxy_html
/usr/sbin/a2enmod proxy_http
/usr/sbin/a2enmod auth_mysql

set -e

#DEBHELPER#

exit 0
