"""Theme support

Revision ID: 27cfcfd0995b
Revises: 2c9cf78e6f4d
Create Date: 2014-07-26 19:06:17.137728

"""

# revision identifiers, used by Alembic.
revision = '27cfcfd0995b'
down_revision = '2c9cf78e6f4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('style', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sectionIcon')
    op.add_column('section', sa.Column('theme_id', sa.String(length=50), server_default='default', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'theme_id')
    op.create_table('sectionIcon',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('iconset_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('iconset_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('icon_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('label', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('theme')
    ### end Alembic commands ###
