"""Initial creation

Revision ID: 294792d73411
Revises: None
Create Date: 2014-03-28 15:46:01.092862

"""

# revision identifiers, used by Alembic.
revision = '294792d73411'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataType',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('reference', sa.Unicode(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pageTheme',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pageIcon',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('iconset_id', sa.String(length=50), nullable=True),
    sa.Column('iconset_name', sa.Unicode(length=50), nullable=True),
    sa.Column('icon_id', sa.String(length=50), nullable=True),
    sa.Column('label', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('icon_id', sa.String(length=50), nullable=True),
    sa.Column('theme_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['pageIcon.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['pageTheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('return_confirmation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.Column('last_value', sa.Unicode(length=50), nullable=True),
    sa.Column('last_received', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['datatype'], ['dataType.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandParam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['datatype'], ['dataType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('widget_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstanceSensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstanceParam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstanceCommand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widgetInstanceCommand')
    op.drop_table('widgetInstanceParam')
    op.drop_table('widgetInstanceSensor')
    op.drop_table('widgetInstance')
    op.drop_table('commandParam')
    op.drop_table('sensor')
    op.drop_table('command')
    op.drop_table('page')
    op.drop_table('pageIcon')
    op.drop_table('widget')
    op.drop_table('pageTheme')
    op.drop_table('device')
    op.drop_table('parameter')
    op.drop_table('dataType')
    ### end Alembic commands ###
