"""Added WidgetDevice table

Revision ID: 2c9cf78e6f4d
Revises: 4e173b30fb97
Create Date: 2014-07-22 21:06:27.753549

"""

# revision identifiers, used by Alembic.
revision = '2c9cf78e6f4d'
down_revision = '4e173b30fb97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgetInstanceDevice',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('instance_id', 'key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widgetInstanceDevice')
    ### end Alembic commands ###
