"""Initial creation

Revision ID: 3cc64bd4e0f9
Revises: None
Create Date: 2014-03-28 15:21:15.245863

"""

# revision identifiers, used by Alembic.
revision = '3cc64bd4e0f9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pageIcon',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('iconset_id', sa.String(length=50), nullable=True),
    sa.Column('iconset_name', sa.Unicode(length=50), nullable=True),
    sa.Column('icon_id', sa.String(length=50), nullable=True),
    sa.Column('label', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataType',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('author', sa.Unicode(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pageTheme',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.Unicode(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packageDependency',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packageDeviceType',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=50), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('configured', sa.Boolean(), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('left', sa.Integer(), nullable=True),
    sa.Column('right', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('icon_id', sa.String(length=50), nullable=True),
    sa.Column('theme_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['icon_id'], ['pageIcon.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['pageTheme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packageUdevRule',
    sa.Column('filename', sa.Unicode(length=50), nullable=False),
    sa.Column('rule', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('model', sa.Unicode(length=255), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('clientConfiguration',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('default', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('client_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('reference', sa.Unicode(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['packageDeviceType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('widget_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packageProduct',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('documentation', sa.Unicode(length=255), nullable=True),
    sa.Column('package_id', sa.String(length=50), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['device_type'], ['packageDeviceType.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.Column('last_value', sa.Unicode(length=50), nullable=True),
    sa.Column('last_received', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['datatype'], ['dataType.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstanceParam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xplCmd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('json_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('return_confirmation', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xplStat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('json_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commandParam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('datatype', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['datatype'], ['dataType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstanceCommand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('command_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['command.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetInstanceSensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['widgetInstance.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widgetInstanceSensor')
    op.drop_table('widgetInstanceCommand')
    op.drop_table('commandParam')
    op.drop_table('xplStat')
    op.drop_table('command')
    op.drop_table('xplCmd')
    op.drop_table('widgetInstanceParam')
    op.drop_table('sensor')
    op.drop_table('packageProduct')
    op.drop_table('widgetInstance')
    op.drop_table('device')
    op.drop_table('clientConfiguration')
    op.drop_table('packageUdevRule')
    op.drop_table('page')
    op.drop_table('client')
    op.drop_table('packageDeviceType')
    op.drop_table('packageDependency')
    op.drop_table('pageTheme')
    op.drop_table('parameter')
    op.drop_table('package')
    op.drop_table('widget')
    op.drop_table('dataType')
    op.drop_table('pageIcon')
    ### end Alembic commands ###
