"""initial version

Revision ID: 4565f497520d
Revises: None
Create Date: 2014-07-05 12:33:58.095401

"""

# revision identifiers, used by Alembic.
revision = '4565f497520d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('command', sa.Column('datatypes', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('command', 'datatypes')
    ### end Alembic commands ###
