"""Added sensor timeout attribute

Revision ID: 55865a33c659
Revises: dcf2a886e7f
Create Date: 2014-08-26 08:33:56.485202

"""

# revision identifiers, used by Alembic.
revision = '55865a33c659'
down_revision = 'dcf2a886e7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('timeout', sa.Integer(), nullable=False, server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'timeout')
    ### end Alembic commands ###
