"""Style option for widgets

Revision ID: dcf2a886e7f
Revises: 27cfcfd0995b
Create Date: 2014-08-04 16:31:24.061097

"""

# revision identifiers, used by Alembic.
revision = 'dcf2a886e7f'
down_revision = '27cfcfd0995b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget', sa.Column('style', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget', 'style')
    ### end Alembic commands ###
